In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [2]:
job= pd.read_csv('/Users/anishgulhane/Downloads/datasets after 14 sept/fake_job_postings.csv')

In [3]:
job.shape

(17880, 35)

In [4]:
job.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
job.tail()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
job.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
Unnamed: 18            17880
Unnamed: 19            17880
Unnamed: 20            17880
Unnamed: 21            17880
Unnamed: 22            17880
Unnamed: 23            17880
Unnamed: 24            17880
Unnamed: 25            17880
Unnamed: 26            17880
Unnamed: 27            17880
Unnamed: 28            17880
Unnamed: 29            17880
Unnamed: 30            17880
Unnamed: 31            17880
Unnamed: 32            17880
Unnamed: 33            17880
Unnamed: 34            17879
dtype: int64

In [7]:
job.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34'],
      dtype='object')

In [8]:
#job['X'] = job['company_profile'].apply(str) + " " +job['salary_range'].apply(str) + " " +job['requirements'].apply(str) + " " +job['benefits'].apply(str) + " " +job['location'].apply(str) + " " +job['description'].apply(str) + " " +job['industry'].apply(str)

#ulternate way of doing this

# 1. List the columns you want to combine
cols_to_concat = [
    'title', 'location', 'department', 'salary_range', 'company_profile', 
    'description', 'requirements', 'benefits', 'telecommuting', 
    'has_company_logo', 'has_questions', 'employment_type', 
    'required_experience', 'required_education', 'industry', 'function'
]

# 2. Fill missing values with an empty string, convert to text, and join with a space
job['X'] = job[cols_to_concat].fillna('').astype(str).agg(' '.join, axis=1)

In [9]:
job['X'] = job['title'].apply(str) + " " + job['location'].apply(str) + " " + job['department'].apply(str) + " " + job['salary_range'].apply(str) + " " + job['company_profile'].apply(str) + " " + job['description'].apply(str) + " " + job['requirements'].apply(str) + " " + job['benefits'].apply(str) + " " + job['telecommuting'].apply(str) + " " + job['has_company_logo'].apply(str) + " " + job['has_questions'].apply(str) + " " + job['employment_type'].apply(str) + " " + job['required_experience'].apply(str) + " " + job['required_education'].apply(str) + " " + job['industry'].apply(str) + " " + job['function'].apply(str)

In [10]:
job = job.rename(columns = {'fraudulent':'Y'})

In [11]:
df = job.loc[:,["X","Y"]]

In [12]:
df.head(1)

                                                   X  Y
0  Marketing Intern US, NY, New York Marketing na...  0

In [13]:
df = df.rename(columns = {'Score': 'Y','Text': 'X'})

In [14]:
df.head()

                                                   X  Y
0  Marketing Intern US, NY, New York Marketing na...  0
1  Customer Service - Cloud Video Production NZ, ...  0
2  Commissioning Machinery Assistant (CMA) US, IA...  0
3  Account Executive - Washington DC US, DC, Wash...  0
4  Bill Review Manager US, FL, Fort Worth nan nan...  0

In [15]:
df.Y.value_counts()

Y
0    17014
1      866
Name: count, dtype: int64

In [16]:
import nltk #  natural language tool kit (library used in NLP)
from nltk.corpus import stopwords

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anishgulhane/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [19]:
len(stopwords.words('english'))

198

In [20]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [21]:
df['X'] = df['X'].str.lower()

In [22]:
l1 = stopwords.words(('english'))
def text_process(mess):
    """
    1. remove the punctuation 
    2. remove the stopwords
    3. return the list of clean textwords
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)

    return[ word for word in nopunc.split() if word not in l1 ]

In [23]:
#df['X'].apply(text_process)# samjhane ke liye

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
# assign a ID/token number to each word

In [25]:



bow_transformer = CountVectorizer(analyzer=text_process).fit(df["X"])

In [26]:
len(bow_transformer.vocabulary_)

174463

In [27]:
print(len(bow_transformer.vocabulary_))

174463

In [28]:
tdm = bow_transformer.transform(df['X'])

In [29]:
tdm.shape

(17880, 174463)

In [30]:
type(tdm)

scipy.sparse._csr.csr_matrix

In [31]:
df.head()

                                                   X  Y
0  marketing intern us, ny, new york marketing na...  0
1  customer service - cloud video production nz, ...  0
2  commissioning machinery assistant (cma) us, ia...  0
3  account executive - washington dc us, dc, wash...  0
4  bill review manager us, fl, fort worth nan nan...  0

In [32]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(tdm, df.Y)

from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import *

train_y = train_y.astype(int)
test_y = test_y.astype(int)

In [33]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(class_weight = "balanced")
logreg.fit(train_x, train_y)#model build

LogisticRegression(class_weight='balanced')

In [34]:
pred = logreg.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y, pred))

[[4207   48]
 [  37  178]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4255
           1       0.79      0.83      0.81       215

    accuracy                           0.98      4470
   macro avg       0.89      0.91      0.90      4470
weighted avg       0.98      0.98      0.98      4470

In [35]:
from sklearn.tree import DecisionTreeClassifier

# Limit max_depth and max_features to heavily speed up training
dt = DecisionTreeClassifier(max_depth=50, max_features='sqrt',class_weight = "balanced")
dt.fit(train_x, train_y)

pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

print(accuracy_score(test_y, pred), " ", 
      recall_score(test_y, pred, average='weighted'), " ", 
      precision_score(test_y, pred, average='weighted'))

[[3852  403]
 [  65  150]]
0.8953020134228188   0.8953020134228188   0.9491519865020578

In [36]:

from sklearn.ensemble import RandomForestClassifier

# Added n_estimators, max_depth, max_features, and n_jobs=-1
rf = RandomForestClassifier(n_estimators=50, max_depth=50, max_features='sqrt', n_jobs=-1, oob_score=True,class_weight = "balanced")
rf.fit(train_x, train_y)

pred = rf.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

# Remember to use average='weighted' here too!
print(accuracy_score(test_y, pred))

[[4203   52]
 [  73  142]]
0.9720357941834452